spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/cheems
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  session:
    timeout: 86400
